// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNfuGKacvBJJF1x02Rm8mOufiudV1dnSU',
    appId: '1:198080770535:web:e1fc50ab5de072a99fcd42',
    messagingSenderId: '198080770535',
    projectId: 'app6-f1b21',
    authDomain: 'app6-f1b21.firebaseapp.com',
    databaseURL: 'https://app6-f1b21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app6-f1b21.appspot.com',
    measurementId: 'G-R3ZZFHLCZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhmL-mcOsqupnbOvRkxE24hon_VO_wfg',
    appId: '1:198080770535:android:13361a34df241ccc9fcd42',
    messagingSenderId: '198080770535',
    projectId: 'app6-f1b21',
    databaseURL: 'https://app6-f1b21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app6-f1b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCWG8dlJbbFDevgAXm44qF48VrRAP79k',
    appId: '1:198080770535:ios:bd7c9638e1cb54279fcd42',
    messagingSenderId: '198080770535',
    projectId: 'app6-f1b21',
    databaseURL: 'https://app6-f1b21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app6-f1b21.appspot.com',
    iosClientId: '198080770535-aoslnr0aputau2ifurej6s74r98mbqvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app-6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCWG8dlJbbFDevgAXm44qF48VrRAP79k',
    appId: '1:198080770535:ios:8ed763de487bf7bf9fcd42',
    messagingSenderId: '198080770535',
    projectId: 'app6-f1b21',
    databaseURL: 'https://app6-f1b21-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app6-f1b21.appspot.com',
    iosClientId: '198080770535-qo4guloggpr05nnds6583759ljoh8q9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.app6',
  );
}
